# permissions for end users to view rollingpodsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rollingpodset-viewer-role
rules:
- apiGroups:
  - apps.michael-diggin.github.io
  resources:
  - rollingpodsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.michael-diggin.github.io
  resources:
  - rollingpodsets/status
  verbs:
  - get
